2013-12-16 11:45:51,259 ERROR: Exception on /static/img/myopenid.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/myopenid.png'
2013-12-16 11:48:19,381 ERROR: Exception on /static/css/bootstrap.min.css [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/css/bootstrap.min.css'
2013-12-16 11:48:19,388 ERROR: Exception on /static/js/bootstrap.min.js [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/js/bootstrap.min.js'
2013-12-16 11:48:19,393 ERROR: Exception on /static/js/moment.min.js [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/js/moment.min.js'
2013-12-16 11:48:19,396 ERROR: Exception on /static/img/google.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/google.png'
2013-12-16 11:48:19,409 ERROR: Exception on /static/img/yahoo.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/yahoo.png'
2013-12-16 11:48:19,425 ERROR: Exception on /static/img/flickr.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/flickr.png'
2013-12-16 11:48:19,437 ERROR: Exception on /static/img/myopenid.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/myopenid.png'
2013-12-16 11:48:19,574 ERROR: Exception on /static/img/google.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/google.png'
2013-12-16 11:48:19,580 ERROR: Exception on /static/img/aol.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/aol.png'
2013-12-16 11:48:21,767 ERROR: Exception on /static/img/google.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/google.png'
2013-12-16 11:48:21,779 ERROR: Exception on /static/img/yahoo.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/yahoo.png'
2013-12-16 11:48:21,792 ERROR: Exception on /static/img/flickr.png [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 616, in send_from_directory
    return send_file(filename, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 13] Permission denied: u'/var/www/flaskr/app/static/img/flickr.png'
